### ISSUE TITLE
every time I launch it gives me a microsoft .NET Framework error

### ISSUE THREAD

**Issue by JakonSU** [Xferno2/Hearts-Of-Iron-IV-Launcher#7] opened 2021-11-22 15:00 UTC
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Hoi4_Launcher.Form1.generateCategories() in G:\Documents\Visual Studio 2017\Projects\Hoi4 Launcher\Hoi4 Launcher\Form1.cs:line 368
   at Hoi4_Launcher.Form1.load() in G:\Documents\Visual Studio 2017\Projects\Hoi4 Launcher\Hoi4 Launcher\Form1.cs:line 113
   at Hoi4_Launcher.Form1.Form1_Load_1(Object sender, EventArgs e) in G:\Documents\Visual Studio 2017\Projects\Hoi4 Launcher\Hoi4 Launcher\Form1.cs:line 103
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at MetroSet_UI.Forms.MetroSetForm.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at MetroSet_UI.Forms.MetroSetForm.WndProc(Message& message)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Hoi4 Launcher
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Games/SteamLibrary/steamapps/common/Hearts%20of%20Iron%20IV/Hoi4%20Launcher.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
MetroSet UI
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
    CodeBase: file:///D:/Games/SteamLibrary/steamapps/common/Hearts%20of%20Iron%20IV/MetroSet%20UI.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
ImgButton
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Games/SteamLibrary/steamapps/common/Hearts%20of%20Iron%20IV/ImgButton.DLL
----------------------------------------
Geckofx-Winforms
    Assembly Version: 45.0.34.0
    Win32 Version: 45.0.34.0
    CodeBase: file:///D:/Games/SteamLibrary/steamapps/common/Hearts%20of%20Iron%20IV/Geckofx-Winforms.DLL
----------------------------------------
Geckofx-Core
    Assembly Version: 45.0.34.0
    Win32 Version: 45.0.34.0
    CodeBase: file:///D:/Games/SteamLibrary/steamapps/common/Hearts%20of%20Iron%20IV/Geckofx-Core.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.1.25517
    CodeBase: file:///D:/Games/SteamLibrary/steamapps/common/Hearts%20of%20Iron%20IV/Newtonsoft.Json.DLL
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by Xferno2** [comment] 2021-11-24 17:03
Which branch of the project are you using? Did you download the pre-release or the latest release?

**Comment by YummYume** [comment] 2021-12-01 21:15
I also get this error when using this [release](https://github.com/Xferno2/Hearts-Of-Iron-IV-Launcher/releases/tag/v0.3.2.1-alpha). I did try to use the [latest release](https://github.com/Xferno2/Hearts-Of-Iron-IV-Launcher/releases/tag/0.2.1) but I was getting another error (not the same one). I really want to use this, I can't stand the Paradox launcher anymore.

**Comment by Xferno2** [comment] 2021-12-01 21:36
This error is so weird I haven't encounter it at all so we will have to try a few things.
First you do have the right release the pre releases are recommended right now, do not try to fix it using the last stable release cuz that's really old.
Second let me ask you do you have any mods installed or any dlc purchased?
Third can you send me a screenshot of the error and the error text but in a pastebin so it can be easier to read?
Forth it might sound stupid but did you unzip everything from the archive?

The answers to this might give me a clue to what's happening cuz it doesn't seem an code from error maybe just the environment is wrong like no dlcs or no mods

**Comment by YummYume** [comment] 2021-12-01 21:55
I have every DLC and do mods. Some of them are local mods. I decided to give this launcher a go mostly because the Paradox launcher decided it was time to kill all my local mods once again. It took a few hours to fix and still takes way too long to load for me to even consider using it again.
I'll send the error tomorrow as I'm not on my computer right now. 
Also yes, I did unzip everything in the root HOI4 folder. Also worth noting that I can still use the launcher despite the error, but no mods/dlcs are available.

**Comment by YummYume** [comment] 2021-12-02 17:23
@Xferno2
Here is the error in [Pastebin](https://pastebin.com/D7cMPqNm). It's basically the same as above.

Screenshot of the error (sorry it's in French) :
![RRbnFfk](https://user-images.githubusercontent.com/61044908/144471699-1870a668-4433-480b-a817-b398a548308e.png)

**Comment by Xferno2** [comment] 2021-12-02 19:46
From the pastebin I think I know what the problem is so thank you, it will probably be fixed with the next release so you will have to wait a few days.  If it's not then I have to look into it further.

**Comment by YummYume** [comment] 2021-12-02 22:18
Alright thanks! 👍

**Comment by YummYume** [comment] 2021-12-06 18:20
@Xferno2 Got a new error now :( System.IndexOutOfRangeException: Index was outside the bounds of the array.
[Pastebin](https://pastebin.com/3sZDkJer)

**Comment by Xferno2** [comment] 2021-12-06 18:50
Could you make an archive with your mod folder from hoi and post it here or any other sharing website? (Documents\Paradox Interactive\Hearts of Iron IV\mod)
I only need ".mod" files so I can debug this issue properly.

**Comment by YummYume** [comment] 2021-12-06 20:46
Here you go : [mods_debug.zip](https://github.com/Xferno2/Hearts-Of-Iron-IV-Launcher/files/7663460/mods_debug.zip)

**Comment by Xferno2** [comment] 2021-12-09 23:31
Try this patch, tell me if it works cuz I don't get any error with your mods but I want to make sure:  [here](https://drive.google.com/file/d/1BtIpeWWAujkpoQBHhYPM7fp13OvwdrIG/view?usp=sharing) it's a drive link cuz the upload size was too big.

**Comment by YummYume** [comment] 2021-12-12 09:49
@Xferno2  So this patch works and launches without any error. I can see my DLCs and mods! But whenever I enable a local mod, it does not take it into account.
![kmVDnsi](https://user-images.githubusercontent.com/61044908/145707744-b6eabc89-9e2e-45f1-9fa7-23052c5fb19d.png)
.

**Comment by Xferno2** [comment] 2021-12-12 13:40
@YummYume I think I know why, I will try patch it and send you the version hopefully that one fixes everything. The launcher was never optimized for local mods that why it has so many problems with that.

**Comment by YummYume** [comment] 2021-12-12 15:33
@Xferno2 Alright thank you!

**Comment by Xferno2** [comment] 2021-12-12 22:08
@YummYume okay try [this](https://drive.google.com/file/d/1BtIpeWWAujkpoQBHhYPM7fp13OvwdrIG/view?usp=sharing)

**Comment by YummYume** [comment] 2021-12-16 21:31
@Xferno2 Amazing! It works perfectly, thanks :)

**Comment by Xferno2** [comment] 2021-12-16 22:23
No problem, glad everything works now.

**Closed by Xferno2** 2021-12-16 22:23 UTC
